name: flutter_integration_example
description: "A Flutter integration example of the Capsule SDK."
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  capsule: ^0.2.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
